### ISSUE TITLE
File system not balanced between disk packs.

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/its#2049]
`^F` in a recent build display this:

```
FREE BLOCKS #2=280 #3=1009 #0=1277 #1=8419 
```

Disk pack 2 is almost full, and 1 is almost unused.

**Comment by larsbrinkhoff** [comment]
@eswenson1, here's an issue I opened for the problem you mentioned recently.

**Comment by larsbrinkhoff** [comment]
As per https://github.com/PDP-10/its/issues/2075#issuecomment-957186042, the code after label QWRO2A seems to be responsible for checking if a pack is getting full and then creating a file on another pack.

I put a breakpoint there and it is indeed called when creating a new file.

**Comment by eswenson1** [comment]
In your debugging, it would be interesting to know the values of QSFT and QFTTHR for the "current writing unit".  

```
        SKIPGE I,QWRU   ;GET CURRENT WRITING UNIT
         JRST QWRO2E    ;NO CURRENT UNIT, GO FIND ONE
        MOVE TT,QSFT(I)
        CAML TT,QFTTHR
         JRST QWRO2B    ;ENOUGH ROOM ON PREFERRED UNIT
```

**Comment by larsbrinkhoff** [comment]
I see this comment, so I'm surprised DSK0: runs out of space so easily.
```
https://github.com/PDP-10/its/issues/2075#issuecomment-957186042
```

**Comment by larsbrinkhoff** [comment]
`QFTTHR` is 600. as in the code above.  `I` is the unit, but it happens to be 3 most of the time.  `QSFT(I)` is over 6000 in this case.

**Comment by larsbrinkhoff** [comment]
I put a :LISTF before and after loading the big sources.tape.  Before there's plenty of space all around:

```
FREE BLOCKS #2=7157 #3=8444 #0=8458 #1=8458
```

But after most of the space on PK2 (which is DSK0) is taken, and PK3 is almost full too:

```
FREE BLOCKS #2=193 #3=719 #0=8458 #1=8458
```

**Comment by larsbrinkhoff** [comment]
On a closer reading, my understanding is that `QWRU` is the "current writing unit", and it remains set to the same unit unless the capacity falls below `QFTTHR`.  At that point the list of units is consulted to find some other unit which remains in effect as the new `QWRU` from then on.  This explains why pack 2 (unit 0) is filled up, and then pack 3.

Maybe this algorithm made sense: if a unit is active, it's quicker to write new files there?  Anyway, it's not ideal for our use case where the build script extracts a large number of files which all end up on pack 2.

**Comment by larsbrinkhoff** [comment]
I added this code to QWRO2A.  Every time QWRO2A is called to figure out which unit to write to, it cycles through all active units.

```
        AOS I,QWRU
        CAIL I,NQS
         SETZB I,QWRU
        SKIPE QACT(I)
         JRST .-4
        JRST QWRO2B
```

It seems to work when it's called, however it's *not* being called every time a file is written.  I suspect this happens when a new directory is created, but I'm not sure yet.

**Comment by eswenson1** [comment]
Is QRSRVP independent of the ability to have second:, third: etc?  That ability is a nice feature, with support built into dired.

**Comment by larsbrinkhoff** [comment]
@eswenson1, I'm not sure.  I checked all QRSRVP conditionals.  There aren't too many of them, and I didn't see anything that would obviously affect the SECOND:, THIRD:, etc devices.

I'm beginning to suspect file allocation works as intented - new files are created on unit 0 and maybe they are supposed to be GFR'ed to SECOND:?  I was thinking the solution might be to turn off QRSRVP to have files more randomly distributed, but when I did that some programs no longer work so the build script hangs.

**Comment by eswenson1** [comment]
Why would some programs no longer work? Can you give an example and what you mean by “no longer work”? I wouldn’t think anything outside ITS would care. 

I do know that there is support for SECOND:, etc. in programs like DiRED, and that is why I asked about any interaction with QRSRVP.

**Comment by eswenson1** [comment]
Are you sure this is related? I can’t see why disabling this would effect building advent.The support in dired is only to provide commands for migrating files to second:. I would think, however, that using these commands when second: doesn’t exist would only give a non-existent device error.— Eric (KC6EJS)On Jan 9, 2023, at 09:39, Lars Brinkhoff ***@***.***> wrote:﻿
For example, 448-point Advent no longer builds.  It hangs when it should prompt for a file name.
What is it DIRED will do with SECOND:?

**Comment by eswenson1** [comment]
Also note that all configurations from the "old days" had QRSRVP set to 1.

**Comment by larsbrinkhoff** [comment]
I'm quite sure.  I ran the build several times with QRSRVP off and it always stops in the same place.  Maybe some bitrot happened that makes QRSRVP=0 no longer work in some odd corner case.

**Comment by eswenson1** [comment]
I checked the system;config from PI and see that *all* configs had this value QRSRVP==1.  The comment next to the default value is:

```
 ;1= Has reserved disk packs (Secondary pack)
```

I think we *want* it on.

**Comment by larsbrinkhoff** [comment]
I agree we should leave it on, since it has been the default for a long time and there's possibly bitrot exposed when turning it off.

But the question remains, what do we do about the disk filling up?  Are new files written to DSK0 by design?  Do we change that, or do we work around it?

**Comment by eswenson1** [comment]
I think we should fix the issue of running out of disk space when there is plenty (on other packs). Perhaps something very simple like keeping some reserved amount of disk space free and forcing the current unit to change to another when there is less than that much free on the current default unit. 

Or perhaps a round robin — rotating the current unit on each new file creation.

**Comment by larsbrinkhoff** [comment]
Right, but how to do that without breaking the current design?  From reading the code it seems to me new files are written to DSK0 by design when QRSRVP is on.  I.e. in this section, QSALLO(H) is set to 0.  If it were set to -1, the file would be written to any unit.  But for some reason, it's not.  I believe the target disk unit is set per directory.

```
QWRO2A:
IFN QRSRVP,[
        SKIPL I,QSALLO(H)
         JRST QWRO2B    ;THIS DIR GOES ON A PARTICULAR UNIT
]
```

I did a round robing thing below this, but it only works for writing existing files.  When QRSRVP is on new files go to DSK0, maybe for a reason.

The DIRSIZ .CALL can be used to get and set the directory disk allocation.  It seems a possible workaround would be to create directories first, then set their disk allocations distributes between all disks, and only then load files from tape.

**Comment by larsbrinkhoff** [comment]
It turns out DUMP can call DIRSIZ to set directory allocations.  By forcibly setting some directories to allocate files on pack 0 (DSK3:), I can get these comfortable numbers after the big sources tape has been read:

```
FREE BLOCKS #2=3896 #3=3346 #0=8458 #1=2352
```

**HOWEVER**, I'm starting to suspect there is a bug somewhere.  New directories are created with "no allocation" which *should* mean files can go on any pack.  But what happens is that `JRST QWRO2B ;THIS DIR GOES ON A PARTICULAR UNIT` is called.  `QSALLO` is only set in two places, one of which is the DIRSIZ call.  Both places look like they do the right thing.  But maybe they're not, **or** maybe QSALLO needs to be set in other places.

**Comment by larsbrinkhoff** [comment]
I now do believe there is a bug related to newly created directories.

If I use the LOAD CRDIR command with DUMP, it will create directories as needed, but `JRST QWRO2B` is called because `QSALLO(H)` is 0.  The same thing happens if I create the directory first, then shortly after run DUMP.

However, if I create the directory and wait a few seconds, QSKBK0+1 sets QSALLO(H).  And after this, DUMP will run fine, `QSALLO(H)` is -1, and `JRST QWRO2A` is *not* called.

**Comment by larsbrinkhoff** [comment]
When a directory is created by referring to `..NEW. (UDIR)`, the `QSALLO(H)` field is not initialized.  So it can contain some random value from before, most likely 0 or -1.  If it's -1, we're in luck and the directory has no allocation.  But if it's 0, the directory is allocated to disk unit 0.

**Comment by eswenson1** [comment]
That's a good find -- we should fix that.  When we load the various minsys/source tapes, does DUMP CRDIR do the right thing?  I think we *do* explicitly create some directories in the build scripts with ..new. (udir), so those, at least would be wrong.  But many directories are created "automatigically" by DUMP.

**Comment by larsbrinkhoff** [comment]
Yes, DUMP CRDIR creates directories.  The ones we create explicitly are not on the tape... or that *should* be the case.

**Comment by eswenson1** [comment]
My question was whether DUMP CRDIR correctly sets the directory allocation for newly-created directories.

**Comment by larsbrinkhoff** [comment]
CRDIR by itself doesn't touch the directory allocation.  If the allocation is unset, the files in the directory can go to any pack.

There's a DUMP command called ALLOC which is used to set the allocation of any directory.  I tested it, and it works.  But it's not used when we extract the large sources tape.

**Comment by larsbrinkhoff** [comment]
I added a simple fix to the ..NEW. (UDIR) code path which just `SETOM QSALLO(H)` and that seems to do the right thing.  After a complete build, I now get this:

```
FREE BLOCKS #2=7187 #3=628 #0=1008 #1=698
```

As we can see, files are not distributed evenly.  But that's not to be expected (yet).  We can see that two packs hover just over 600 which is the lower limit set by `QFTTHR` (see above).

I *also* made another hack to have `QWRU` (current writing unit) rotate around the packs to distribute files better.  I will test that now.

**Comment by larsbrinkhoff** [comment]
Fixed by #2142.

**Comment by eswenson1** [comment]
> CRDIR by itself doesn't touch the directory allocation. If the allocation is unset, the files in the directory can go to any pack.
> 
> There's a DUMP command called ALLOC which is used to set the allocation of any directory. I tested it, and it works. But it's not used when we extract the large sources tape.

I guess I must have misunderstood your findings. You said that ^R foo;..new.. (udir) didn’t set QSALLOC(H), which left a random value from before. My question was whether DUMP CRDIR, which MAY create a new directory, also results in an unset and bogus QSALLOC(H). Because if that were the case, then both directories we create by hand in the build and directories that were created by DUMP would have possibly garbage values for QSALLOC(H).

So does DUMP have the same problem as ..new. (udir)?

**Comment by larsbrinkhoff** [comment]
Yes, DUMP has the same problem because CRDIR uses the ..NEW. (UDIR) mechanism.

**Comment by eswenson1** [comment]
I've been running out of disk space on ES a lot lately (been adding a lot of files).  I have three RP06s.  DSKUSE reports:

```
Drive           DK0:    DK1:    DK2:

Pack #               0       1       2
Disk size        38164   38164   38164

Available        36609   36609   36609
Free space        1759     931    8256
``` 

(Yes, I've moved a lot of stuff from pk0: to pk2: today, so I'm not out of space on pk0: now).  

However, files keep going to pk0: and I keep having to use DIRED to move them to pk2:.  I checked and it seems I do have the fixes in #2142 to SYSTEM; DISK >.  And I did build (and am running) an ITS I built after incorporating those fixes.

If I check the running ITS, I see:

```
ES>sys◊j
ES>QWRO2A/   SKIPL I,QSALLO(H)
QWRO2A+1/   JRST QWRO2B
QWRO2A+2/   SKIPGE QWRU
QWRO2A+3/   JRST QWRO2E
QWRO2A+4/   AOS I,QWRU
QWRO2A+5/   CAIL I,C
QWRO2A+6/   SETZB I,QWRU
QWRO2A+7/   SKIPE QACT(I)
QWRO2A+10/   JRST QWRO2A+4
QWRO2A+11/   MOVE TT,QSFT(I)
```

So, the fix doesn't seem to be working for me.  @larsbrinkhoff Am I doing something wrong?  What do you suggest I investigate or fix?

**Comment by eswenson1** [comment]
Actually, the fix (as written) does work.  But it still doesn't "solve" the problem.  So when adding LOTS of files, on a three-disk system, every third file will go to pk0, regardless of space.  So because I added a lot of files, we sequenced through each disk, but since pk0 was really low to begin with, we soon ran out of disk space on pk0 again.  How can we get it to choose a different disk when  the space on SWRU is low?

Here is evidence that it is working as written:

```
sys◊j
ES>qwru/   A   =1
:copy ejs;ejs login,ejs4;aaa 1
ES>?? qwru/   B   =2
:copy ejs;ejs login,ejs4;aaa 2
ES>qwru/   B
:copy ejs;ejs login,ejs4;aaa 3
ES>qwru/   0
:find ejs4;aaa
ES:EJS4;
  2   AAA    1        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  0   AAA    2        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  0   AAA    3        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS

:KILL  SYS◊J
ES>qwru/   0
:copy ejs;ejs login,ejs4;aaa 4
ES>qwru/   A
:copy ejs;ejs login,ejs4;aaa 5
ES>qwru/   B
:copy ejs;ejs login,ejs4;aaa 6
ES>qwru/   0
:find ejs4;aaa
ES:EJS4;
  2   AAA    1        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  0   AAA    2        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  0   AAA    3        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  1   AAA    4        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  2   AAA    5        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS
  0   AAA    6        0  +59  ! 2/17/2023 11:28:42 (2/23/2023) EJS

:KILL  SYS◊J
ES>
```

**Comment by larsbrinkhoff** [comment]
Right, my fix doesn't consider the available space.  It just rotates through the disk packs round robin style.

However, there's another place that should check the number of free blocks against the number in QFTTHR.  Does that not work for you?
